version: 0.2

#TODO: Move all constatns to environment variables
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - start-dockerd
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - pip install -r src/requirements.txt
      - bash src/setup.sh $FRAMEWORK
      - yamllint -d .yamllint *.yml
  build:
    commands:
      - echo Build started on `date`
      - echo Fetching s3 binary for PT EIA...
      - aws s3 cp s3://pytorch-eia-beta/openssl_fix/torch_eia-1.3.1-cp36-cp36m-manylinux1_x86_64.whl pytorch/inference/docker/build_artifacts/torch_eia-1.3.1-cp36-cp36m-manylinux1_x86_64.whl
      - echo Building the Docker image...
      - |
        if expr "${CODEBUILD_BUILD_ARN}" : ".*eia" >/dev/null; then
          if expr "${CODEBUILD_BUILD_ARN}" : ".*tensorflow-1" >/dev/null; then
            python src/main.py --buildspec $FRAMEWORK/buildspec-tf1-eia.yml --framework $FRAMEWORK
          else
            python src/main.py --buildspec $FRAMEWORK/buildspec-eia.yml --framework $FRAMEWORK
          fi
        else
          if expr "${CODEBUILD_BUILD_ARN}" : ".*tensorflow-1" >/dev/null; then
            python src/main.py --buildspec $FRAMEWORK/buildspec-tf1.yml --framework $FRAMEWORK
          else
            python src/main.py --buildspec $FRAMEWORK/buildspec.yml --framework $FRAMEWORK
          fi
        fi
  post_build:
    commands:
      - echo Build step finished on `date`
      - echo Starting test jobs
      - python src/start_testbuilds.py
artifacts:
  files:
    - $HOME/test_type_images.json
  name: DLC_IMAGES_JSON
  discard-paths: yes
